application: pictexts
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /assets
  static_dir: assets
- url: /slideshow/.*
  script: pictexts.app
